version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_USER: vipul
      POSTGRES_PASSWORD: pawar
      POSTGRES_DB: testDB
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
    - "5435:5432"

  web:
    build: .
    container_name: backend-app
  
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8090:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
volumes:
  postgres_data:
    driver: local
