name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies with Poetry
        run: |
          cd backend
          pip install poetry
          poetry install

      - name: Lint code with Black
        run: |
          cd backend
          poetry add --dev black
          poetry run black --check .

      - name: Run tests
        run: |
          cd backend
          poetry add pytest
          poetry run pytest
